[package]
name = "potassium_oxide"
version = "0.1.0"
edition = "2021"


[dependencies]
ctrlc = "3.2"
dirs = "4.0.0"
dns-lookup = "1.0.8"
parking_lot = "0.11"
serde = { version = "1.0", features = ["derive"] }
toml = { version = "0.5.8", features = ["preserve_order"] }
