# Options for authentication with Twitch.
[auth]
username = "xXxAUCTIONZ_420xXx"
oauth = "oauth:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"


# Auction options: These can be overridden with channel-specific configuration,
#   or by including extra parameters when starting an Auction.
[auction]
# The time for which an Auction will be open, in seconds.
duration = 180

# Helmets protect against snipers. If someone attempts to input a bid when the
#   remaining time (in seconds) is below the Helmet value, the Helmet value is
#   added to the timer.
helmet = 15

# Maximum amount by which a new bid is allowed to exceed the previous.
max_raise = 500
# Minimum acceptable value for the first bid.
min_bid = 5

# If this is true, the FIRST BID may not be higher than the sum of the mininum
#   bid and the maximum raise. For instance, if the minimum bid is $10 and the
#   maximum raise is $100, the first bid may not be more than $110. If this is
#   false, the first bid may be any amount.
# TODO: Not yet implemented.
enforce_max_raise_on_first = true

# The verb that describes the payment method to be used by the winner of an
#   Auction. For instance, if the proceeds go to charity, "donate" may be
#   preferable; If the payment is to be in Bits, "cheer" would be the most
#   descriptive.
verb = "tip"

# Whether to save a summary file of each Auction. The summary file will be in
#   TOML format (the same as this config file), and will contain the settings
#   used for the Auction, as well as all bids. Its location will be printed on
#   Standard Output.
summary = true


# Bot options: These control behavior on all channels.
[bot]
# By default, the Broadcaster and Moderators of a channel can control Auctions
#   in their own channel. This option is a list of usernames that are allowed to
#   control Auctions in ANY channel; Intended for cases where the maintainer of
#   this instance is not a Moderator.
admins = []

# Commands invoked by any username in this list will not be processed.
ignore = []

# With this enabled, Command invocations will be parsed more carefully, allowing
#   arguments to include spaces by enclosing them in quotation marks. Also, a
#   semicolon will be treated as the end of the command, allowing a user to add
#   trailing text to a message without it being interpreted as Command input.
parse_commands = true

# Prefix for commands. Any message that begins with this string will be taken as
#   a command invocation.
prefix = "+"

# Number of seconds to wait before trying to reconnect.
reconnect = 5

# An optional path to be used to write a CSV file keeping track of all past
#   Auctions. If this file does not exist, it will be created with the correct
#   column headings. If it does exist, Auction records will be appended to it,
#   under the assumption that it already has the correct headings. You should
#   make sure that it does not exist yet when you first enable this setting.
#
# This setting will not do anything if the bot has been compiled without CSV
#   output support.
#file_csv = "~/k2o-auctions.csv"


# Channel-specific overrides for Auction options.
[channel.gamesdonequick]
duration = 10
helmet = 1
verb = "donate"
